name: Mutation tests

on:
  workflow_call:
    inputs:
      test-group:
        type: string
        required: true
        description: One of unit, db, api or cli

jobs:
  mutation-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: [ '8.1' ]
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/actions/ci-setup'
        with:
          php-version: ${{ matrix.php-version }}
          extensions-cache-key: mutation-tests-extensions-${{ matrix.php-version }}-${{ inputs.test-group }}
      - uses: actions/download-artifact@v3
        with:
          path: build
      - if: ${{ inputs.test-group == 'unit' }}
        run: composer infect:ci:unit
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
      - if: ${{ inputs.test-group != 'unit' }}
        run: composer infect:ci:${{ inputs.test-group }}
